#!/bin/sh

bspc monitor -d web dev music chat misc

# bspc rule -a "Firefox Developer Edition" desktop=^1
# bspc rule -a "jetbrains-idea" desktop=^2
bspc rule -a "Spotify" desktop=^3
bspc rule -a "Discord" desktop=^4
bspc rule -a "Slack" desktop=^4

bspc config normal_border_color         "#2b1430"
bspc config focused_border_color        "#c349af"
bspc config presel_feedback_color       "#c349af"
bspc config automatic_scheme            longest_side
bspc config initial_polarity            second_child
bspc config split_ratio                 0.62
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config single_monocle              true
bspc config focus_follows_pointer       true
bspc config pointer_follows_focus       false
bspc config pointer_follows_monitor     true
bspc config window_gap                  8
bspc config border_width                2
